kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-global-read
subjects:
  - kind: ServiceAccount
    name: {{ .Values.subjects.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: agent-configmap-reader
  apiGroup: rbac.authorization.k8s.io
