apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-apps

resources:
  - namespace.yaml
  - test-metric-app.yaml
  - http-metric-test-app.yaml
  - ingress.yaml

configMapGenerator:
  - name: environment-config
    envs:
      - .env

replacements:
  - source:
      kind: ConfigMap
      name: environment-config
      fieldPath: data.TEST_METRIC_APP_IMAGE
    targets:
      - select:
          kind: StatefulSet
          name: test-metric-app
        fieldPaths:
          - spec.template.spec.containers.[name=test-metric-app].image
  - source:
      kind: ConfigMap
      name: environment-config
      fieldPath: data.HTTP_METRIC_TEST_APP_IMAGE
    targets:
      - select:
          kind: StatefulSet
          name: http-metric-test-app
        fieldPaths:
          - spec.template.spec.containers.[name=http-metric-test-app].image
