include: .gitlab-ci/shared-pipeline-variables.yml

stages:
  - build-and-test
  - deploy

frontend-build-pipeline:
  stage: build-and-test
  trigger:
    include: .gitlab-ci/frontend-build-pipeline.yml
    strategy: depend

backend-build-pipeline:
  stage: build-and-test
  trigger:
    include: .gitlab-ci/backend-build-pipeline.yml
    strategy: depend

chart-build-pipeline:
  stage: build-and-test
  trigger:
    include: .gitlab-ci/chart-build-pipeline.yml
    strategy: depend

alerting-test-app-build-pipeline:
  stage: build-and-test
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH_NAME && $CI_COMMIT_TAG == null
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  trigger:
    include: .gitlab-ci/alerting-test-app-build-pipeline.yml
    strategy: depend

deployment-pipeline:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH_NAME && $CI_COMMIT_TAG == null
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  trigger:
    include: .gitlab-ci/deployment-pipeline.yml
    strategy: depend
