FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /sonar/sonar-agent
COPY sonar-agent/sonar-agent.csproj .
RUN mkdir /sonar/sonar-core
COPY sonar-core/sonar-core.csproj /sonar/sonar-core
COPY shared.props /sonar
RUN dotnet restore
COPY sonar-agent .
COPY sonar-core /sonar/sonar-core
RUN dotnet build -c Release

FROM mcr.microsoft.com/dotnet/runtime:6.0

WORKDIR /sonar/sonar-agent
COPY --from=build /sonar/sonar-agent/bin/Release/net6.0/* .
COPY --from=build /sonar/sonar-agent/appsettings.json .
ENTRYPOINT ["/sonar/sonar-agent/sonar-agent.exe"]