version: "3.9"
services:
  postgresql:
    image: postgres:14-alpine
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    volumes:
      - "dataVolume:/var/lib/postgresql/data:rw"
    networks:
      - "shared"

volumes:
  dataVolume: {}

networks:
  shared:
