FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine3.19 AS build
LABEL org.opencontainers.image.licenses="CC0-1.0"
LABEL io.artifacthub.package.license="CC0-1.0"
WORKDIR /sonar/sonar-agent
COPY sonar-agent/sonar-agent.csproj .
RUN mkdir /sonar/sonar-core
COPY sonar-core/sonar-core.csproj /sonar/sonar-core
COPY shared.props /sonar
RUN dotnet restore
COPY sonar-agent .
COPY sonar-core /sonar/sonar-core
RUN dotnet build -c Release

FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine3.19
LABEL org.opencontainers.image.licenses="CC0-1.0"
LABEL io.artifacthub.package.license="CC0-1.0"
# make sure we are running the most recent version of these libraries
RUN apk upgrade --no-cache libssl3 libcrypto3
RUN apk add --no-cache tzdata
# remove busybox (must be after usage of apk)
RUN rm /bin/*

WORKDIR /sonar/sonar-agent
COPY --from=build /sonar/sonar-agent/bin/Release/net8.0/* .
ENTRYPOINT ["/sonar/sonar-agent/sonar-agent.exe"]
