FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18 AS build
WORKDIR /sonar/sonar-agent
COPY sonar-agent/sonar-agent.csproj .
RUN mkdir /sonar/sonar-core
COPY sonar-core/sonar-core.csproj /sonar/sonar-core
COPY shared.props /sonar
RUN dotnet restore
COPY sonar-agent .
COPY sonar-core /sonar/sonar-core
RUN dotnet build -c Release

FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine3.18

# make sure we are running the most recent version of these libraries
RUN apk upgrade --no-cache libssl3 libcrypto3

# remove busybox (must be after usage of apk)
RUN rm /bin/*

WORKDIR /sonar/sonar-agent
COPY --from=build /sonar/sonar-agent/bin/Release/net7.0/* .
ENTRYPOINT ["/sonar/sonar-agent/sonar-agent.exe"]
