FROM artifactory.cloud.cms.gov/docker/node:18.18-alpine3.18 AS builder
WORKDIR /sonar/sonar-ui
COPY sonar-ui/package.json .
COPY sonar-ui/package-lock.json .
RUN npm ci
COPY sonar-ui .
RUN npm run build

CMD ["npm", "start"]

FROM artifactory.cloud.cms.gov/docker/nginx:1.25-alpine-slim

# make sure we are running the most recent version of these libraries
RUN apk upgrade --no-cache libssl3 libcrypto3

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

# remove busybox (after usage of rm)
RUN rm /bin/*

COPY --from=builder /sonar/sonar-ui/build .
COPY --from=builder /sonar/sonar-ui/default.conf /etc/nginx/conf.d/

EXPOSE 8080
ENTRYPOINT ["nginx", "-g", "daemon off;"]
