global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
- job_name: alertmanager
  static_configs:
  - targets: [ "alertmanager:9093" ]
- job_name: test-metric-app
  dns_sd_configs:
  - names:
    - test-metric-app
    type: A
    port: 2020
- job_name: sonar-agent
  dns_sd_configs:
    - names:
        - sonar-agent
      type: A
      port: 2020
# Uncomment to scrape sonar-api running on host machine
# - job_name: sonar-api
#   scrape_interval: 10s
#   static_configs:
#     - targets: ["host.docker.internal:8081"]
# Uncomment to scrape sonar-agent running on host machine
# - job_name: "sonar-agent"
#   scrape_interval: 10s
#   static_configs:
#     - targets: ["host.docker.internal:1234"]
