{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
spec:
  podSelector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Enable connections to the cluster DNS service
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.networkPolicies.defaultAllowWithinCluster }}
    # Enable connections to all pods in the cluster
    - to:
        - namespaceSelector: {}
    {{- end }}
    {{- with .Values.networkPolicies.additionalEgressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
