{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  podSelector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress: {{ if empty .Values.networkPolicies.additionalIngressRules }}[]{{ end }}
    {{- with .Values.networkPolicies.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
