include: .gitlab-ci/shared-pipeline-variables.yml

stages:
  - deploy

.deploy:
  stage: deploy
  trigger:
    include:
      - project: $PIPELINE_TRIGGERS_PROJECT
        ref: $PIPELINE_TRIGGERS_VERSION
        file: deployment.yaml
    strategy: depend

.api-deploy-vars: &api-deploy-vars
  TARGET_SERVICE: $API_PROJECT_NAME
  APP_IMAGE_SRC: $API_APP_IMAGE_SRC

.ui-deploy-vars: &ui-deploy-vars
  TARGET_SERVICE: $UI_PROJECT_NAME
  APP_IMAGE_SRC: $UI_APP_IMAGE_SRC

# Automatic deployment pipeline trigger jobs for lower realms.
deploy-api-dev:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH_NAME && $CI_COMMIT_TAG == null
  variables:
    TARGET_ENVIRONMENTS: "environments/dev environments/batcave-dev environments/k3d environments/impl"
    <<: *api-deploy-vars

deploy-ui-dev:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $MAIN_BRANCH_NAME && $CI_COMMIT_TAG == null
  variables:
    TARGET_ENVIRONMENTS: "environments/dev environments/batcave-dev environments/k3d environments/impl"
    <<: *ui-deploy-vars

# Deployment pipeline trigger jobs for the upper realms; automatic deployment for test, manual for prod.
# However, these jobs run under different conditions (orthogonal to the lower realm conditions) and
# don't depend on the lower realm jobs; they form a different "chain" of deployments.
deploy-api-test:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  variables:
    TARGET_ENVIRONMENT: test
    <<: *api-deploy-vars
    APP_IMAGE_TAG: $CI_COMMIT_TAG

deploy-ui-test:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  variables:
    TARGET_ENVIRONMENT: test
    <<: *ui-deploy-vars
    APP_IMAGE_TAG: $CI_COMMIT_TAG

deploy-api-prod:
  needs: [ deploy-api-test ]
  extends: .deploy
  rules:
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  when: manual
  variables:
    TARGET_ENVIRONMENT: prod
    <<: *api-deploy-vars
    APP_IMAGE_TAG: $CI_COMMIT_TAG

deploy-ui-prod:
  needs: [ deploy-ui-test ]
  extends: .deploy
  rules:
    - if: $CI_COMMIT_TAG =~ $APP_VERSION_TAG_REGEX
  when: manual
  variables:
    TARGET_ENVIRONMENT: prod
    <<: *ui-deploy-vars
    APP_IMAGE_TAG: $CI_COMMIT_TAG
