# Default values for sonar-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: null
serviceAccountName: sonar-api-service-account
hosts: "*"
createSonarSecret: true
sonarSecretName: sonar-api-secrets

global:
  okta:
    oktaDomain: https://impl.idp.idm.cms.gov
    authorizationServerId: auscal28z5MWVemkB297
    audience: 0oak4bxc9roSv6aLz297

replicaCount: 1

image:
  repository: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/oit/waynetech/sonar-api
  # override to specify a specific image tag, defaults to the appVersion of the chart
  # tag: latest
  pullPolicy: Always

role:
  nameOverride: null
  additionalRules: null

imagePullSecrets: []

registryCredentials: null

podAnnotations: {}

resources:
  limits:
    cpu: "0.25"
    memory: "512Mi"
  requests:
    cpu: "0.1"
    memory: "64Mi"

nodeSelector: {}

tolerations: []

affinity: {}

sonarConfig:
  legacyEndpoint:
    enabled: false
  UI:
    enabled: true

  apiKey: test+api+key+do+not+use+in+production+xxxxx=
  allowedOrigin: ["*"]
  sonarEnvironment: sonar

  smtpSettings:
    sender: noreply+sonar-alerts@cms.hhs.gov
    host: smtp.cloud.internal.cms.gov
    port: 465

  kubernetesApiAccess:
    isEnabled: true
    isInCluster: true
    targetNamespace: sonar

  database:
    enabled: false #Helm deployment of postgresql
    host: host.k3d.internal #sonar-api-postgresql.sonar.svc.cluster.local
    protocol: null
    port: null
    username: root
    password: password
    database: sonar

  prometheus:
    host: null #sonar-api-prometheus-server-headless.sonar.svc.cluster.local
    protocol: null
    port: null

  alertmanager:
    host: null #sonar-api-alertmanager-headless.sonar.svc.cluster.local
    protocol: null
    port: null

postgresql:
  auth:
    existingSecret: sonar-api-secrets
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
  image:
    repository: bitnami/postgresql
    tag: 14

prometheus:
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kube-state-metrics:
    enabled: false

  imagePullSecrets:
    - name: artifactory-registry

  server:
    global:
      # scrape_interval and evaluation_interval should match props in sonar-api::Cms.BatCave.Sonar.Prometheus.IPrometheusService
      scrape_interval: 3m
      evaluation_interval: 1m
    image:
      repository: prom/prometheus
      tag: v2.45.0
    extraFlags:
      - web.enable-lifecycle
      - web.enable-remote-write-receiver
    tolerations:
      - key: "sonar"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "bat_app"
        operator: "Equal"
        value: "sonar"
        effect: "NoSchedule"
    service:
      enabled: false
    statefulSet:
      enabled: true
      headless:
        servicePort: 9090

  serverFiles:
    prometheus.yml:
      rule_files:
        - "/etc/config/alerting_rules.yml"
        - "/sonar-alerting-rules/alerting-rules.yaml"
      scrape_configs:
        - job_name: "alertmanager"
          static_configs:
            - targets: [ "sonar-api-alertmanager-headless:9093" ]
    alerting_rules.yml:
      groups:
        - name: self-health-alerting
          rules:
            - alert: always-firing
              expr: vector(1)
              for: 0s
              labels:
                purpose: self-health-alerting
              annotations:
                description: An always-firing alert to ensure the alerting pathway from Prometheus to Alertmanager is working.



    alertmanagers:
      - static_configs:
          - targets: [ "sonar-api-alertmanager-headless:9093" ]

    resources:
      limits:
        cpu: 1
        memory: 2048Mi
      requests:
        cpu: 1
        memory: 2048Mi

    extraVolumeMounts:
      - name: config-rule-volume
        mountPath: /sonar-alerting-rules
    extraVolumes:
      - name: config-rule-volume
        configMap:
          name: sonar-alerting-rules
          optional: true

  configmapReload:
    image:
      repository: ghcr.io/prometheus-operator/prometheus-config-reloader
      tag: v0.66.0
    prometheus:
      extraVolumeMounts:
        - name: config-rule-volume
          mountPath: /etc/config/sonar-alerting-rules

  alertmanager:
    enabled: true
    config:
      # Disable the creation of the default alertmanager config
      enabled: false
    imagePullSecrets:
      - name: artifactory-registry
    name: sonar-alertmanager
    image:
      #repository: artifactory.cloud.cms.gov/batcave-docker/ironbank/opensource/prometheus/alertmanager
      repository: prom/alertmanager
      tag: v0.25.0
    tolerations:
      - key: "sonar"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "bat_app"
        operator: "Equal"
        value: "sonar"
        effect: "NoSchedule"
    extraArgs:
      "config.file": "/sonar-config/alertmanager-config.yaml"
    configmapReload:
      enabled: true
      extraVolumeMounts:
        - name: config-secrets
          mountPath: /etc/alertmanager/secrets
    extraVolumeMounts:
      - name: config
        mountPath: /sonar-config
      - name: config-secrets
        mountPath: /sonar-config/secrets
      - name: templates
        mountPath: /sonar-config/templates
    extraVolumes:
      - name: config
        configMap:
          name: sonar-alertmanager-config
          optional: true
      - name: config-secrets
        secret:
          secretName: sonar-alerting-secrets
          optional: true
      - name: templates
        configMap:
          name: sonar-alertmanager-templates
