apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonar

resources:
  - postgres.yaml
  - prometheus-svc.yaml
  - loki.yaml
  - sonar-api.yaml
  - sonar-ui.yaml
  - ingress.yaml

configMapGenerator:
  - name: environment-config
    envs:
      - .env
  - name: appsettings
    files:
      - appsettings.json=appsettings.k3d.json


replacements:
  - source:
      kind: ConfigMap
      name: environment-config
      fieldPath: data.SONAR_API_IMAGE
    targets:
      - select:
          kind: Deployment
          name: sonar-api
        fieldPaths:
          - spec.template.spec.containers.[name=sonar-api].image
  - source:
      kind: ConfigMap
      name: environment-config
      fieldPath: data.SONAR_UI_IMAGE
    targets:
      - select:
          kind: Deployment
          name: sonar-ui
        fieldPaths:
          - spec.template.spec.containers.[name=sonar-ui].image
