apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonar

resources:
  - postgres.yaml
  - prometheus-svc.yaml
  - loki.yaml
  - sonar-api.yaml

configMapGenerator:
  - name: environment-config
    envs:
      - .env

replacements:
  - source:
      kind: ConfigMap
      name: environment-config
      fieldPath: data.SONAR_API_IMAGE
    targets:
      - select:
          kind: Deployment
          name: sonar-api
        fieldPaths:
          - spec.template.spec.containers.[name=sonar-api].image
