apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  PROMETHEUS__HOST: "prometheus"
  DATABASE__HOST: "postgres"
  SONARHEALTHCHECK__SONARENVIRONMENT: "k3d-local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonar-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonar-api
    spec:
      containers:
        - name: sonar-api
          image: sonarapi:testing
          imagePullPolicy: Always
          workingDir: /sonar/sonar-api
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: default-api-key
            - configMapRef:
                name: app-env
          env:
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_PASSWORD
            - name: Database__Username
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_USER
            - name: Database__Database
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_DB
          securityContext:
            allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-api
spec:
  selector:
    app.kubernetes.io/name: sonar-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
