global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
- job_name: test-metric-app
  dns_sd_configs:
  - names:
    - test-metric-app
    type: A
    port: 2020
- job_name: prometheus
  static_configs:
    - targets:
        - localhost:9090 # prometheus endpoint address
