apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap-file
data:
  appsettings.k8s.json: |
    {
      "ApiConfig": {
        "Environment": {{ quote .Values.apiConfig.environment }},
        "Tenant": {{ quote .Values.apiConfig.tenant }},
        "BaseUrl": {{ quote .Values.apiConfig.baseUrl }}
      },
      "Prometheus": {
        {{ if .Values.prometheus.port }}
        "Port": {{ quote .Values.prometheus.host }},
        {{ end }}
        {{ if .Values.prometheus.protocol }}
        "Protocol": {{ quote .Values.prometheus.protocol }},
        {{ end }}
        "Host": {{ quote .Values.prometheus.host }}
      },
      "Loki": {
        {{ if .Values.loki.port }}
        "Port": {{ quote .Values.loki.host }},
        {{ end }}
        {{ if .Values.loki.protocol }}
        "Protocol": {{ quote .Values.loki.protocol }},
        {{ end }}
        "Host": {{ quote .Values.loki.host }}
      }
      {{- if .Values.apiConfig.reportingInterval }},
      "AgentConfig": {
        "AgentInterval": {{ .Values.apiConfig.reportingInterval }}
      }
      {{- end }}
    }
