apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap-file
data:
  appsettings.k8s.json: |
    {
      "ApiConfig": {
        "Environment": {{ quote .Values.apiConfig.environment }},
        "BaseUrl": {{ quote .Values.apiConfig.baseUrl }},
        {{- if .Values.apiConfig.apiKeyId }}
        "ApiKeyId": {{ quote .Values.apiConfig.apiKeyId }}
        {{- end }}
      },
      "Prometheus": {
        {{- if .Values.prometheus.port }}
        "Port": {{ quote .Values.prometheus.host }},
        {{- end }}
        {{- if .Values.prometheus.protocol }}
        "Protocol": {{ quote .Values.prometheus.protocol }},
        {{- end }}
        "Host": {{ quote .Values.prometheus.host }}
      },
      "Loki": {
        {{- if .Values.loki.port }}
        "Port": {{ quote .Values.loki.host }},
        {{- end }}
        {{- if .Values.loki.protocol }}
        "Protocol": {{ quote .Values.loki.protocol }},
        {{- end }}
        "Host": {{ quote .Values.loki.host }}
      }
      {{- if .Values.apiConfig.reportingInterval }},
      "AgentConfig": {
        {{- if .Values.serviceAccountName }}
        "InClusterConfig": true,
        {{- end }}
        "DefaultTenant": {{ quote .Values.apiConfig.tenant }},
        "AgentInterval": {{ .Values.apiConfig.reportingInterval }}
      }
      {{- end }}
    }
