apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap-file
data:
  appsettings.k8s.json: |
    {
      "ApiConfig": {
        "Environment": {{ quote .Values.apiConfig.environment }},
        "Tenant": {{ quote .Values.apiConfig.tenant }},
        "BaseUrl": {{ quote .Values.apiConfig.baseUrl }}
      },
      "Prometheus": {
        "Host": {{ quote .Values.prometheus.host }}
      },
      "Loki": {
        "Host": {{ quote .Values.loki.host }}
      }
    }
