apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-configmap
data:
  appsettings.json: |
    {
      "ApiConfig": {
        "Environment": {{ .Values.apiConfig.environment }},
        "Tenant": {{ .Values.apiConfig.tenant }},
        "BaseUrl": {{ .Values.apiConfig.baseUrl }}
      },
      "Prometheus": {
        "Host": {{ .Values.prometheus.host }}
      },
      "Loki": {
        "Host": {{ .Values.loki.host }}
      }
    }
