{{- if .Values.registryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "containerRegistrySecret" . }}
{{- end }}
