apiVersion: v1
kind: Secret
metadata:
  name: sonar-agent-secrets
type: Opaque
data:
  apiKey: {{ b64enc .Values.apikey }}

#apiKey is based encoded 64
#Value decoded should be xNAFkXO8u4FUrtSG5m+ikTmIe7AJ+b0YiP19QuQzTRA=
#base64 <<< "String"
#base64 -D <<< "64Encoded String"
