{{if .Values.configs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configmap-file
data:
  {{- range $key, $value := .Values.configs }}
    {{ $key }}: |
      {{ include "serviceConfig" $value | indent 6 | trim }}
  {{- end }}
{{- end }}
