apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonar-agent.fullname" . }}
  labels:
    {{- include "sonar-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sonar-agent.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-metrics
    port: 2020
    protocol: TCP
