apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonar-agent.fullname" . }}
  labels:
    app.kubernetes.io/instance: sonar-agent
    app.kubernetes.io/name: sonar-agent
spec:
  type: ClusterIP
  selector:
    {{- include "sonar-agent.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-metrics
    port: 2020
    protocol: TCP