apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonar-agent
spec:
  endpoints:
    - honorLabels: true
      interval: 1m
      path: /metrics
      port: http-metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        insecureSkipVerify: true
        keyFile: /etc/prom-certs/key.pem
      scrapeTimeout: 30s
  jobLabel: sonar-agent
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
  selector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6}}
