apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configmap-file
data:
  {{- range $obj := .Values.configs }}
    {{ $obj.key }}: {{ $obj.config | toJson | quote | indent 4 | trim  }}
  {{- end }}
