apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sonar-agent.fullname" . }}
  labels:
    {{- include "sonar-agent.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sonar-agent.fullname" . }}
  selector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- $combinedAnnotations := .Values.podAnnotations | default (dict) }}
      {{- if .Values.registryCredentials }}
      {{-   $combinedAnnotations = merge $combinedAnnotations (dict "container-registry-secret-version" (toJson .Values.registryCredentials | sha256sum)) }}
      {{- end }}
      {{- $_ := set $combinedAnnotations "checksum/apiConfig" (toJson .Values.apiConfig | sha256sum) }}
      {{- $_ = set $combinedAnnotations "checksum/loki" (toJson .Values.loki | sha256sum) }}
      {{- $_ = set $combinedAnnotations "checksum/prometheus" (toJson .Values.prometheus | sha256sum) }}
      {{- $_ = set $combinedAnnotations "checksum/serviceConfigs" (toJson .Values.configs | sha256sum) }}
      {{- with $combinedAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonar-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- else if .Values.registryCredentials }}
      imagePullSecrets:
        - name: container-registry-credentials
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      volumes:
        - name: appsettings-configmap
          configMap:
            name: appsettings-configmap-file
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: service-configmap
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: service-configmap-file
            # An array of keys from the ConfigMap to create as files
            items:
              {{- range $key, $_ := .Values.configs }}
              - key: {{ $key }}
                path: {{ $key }}.yaml
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --appsettings-location
            - ./settings
            {{- if .Values.kubernetesServiceConfig.enabled }}
            - --kubernetes-configuration
            {{- end }}
            {{- with .Values.configs }}
            - -f
            {{-   $ordering := list }}
            {{-   range $key, $value := . }}
            {{-     $ordering = append $ordering (printf "%03d_%s" (get $value "order" | default 0 | int) $key) }}
            {{-   end }}
            {{-   $ordering = sortAlpha $ordering }}
            {{-   $orderedKeys := list }}
            {{-   range $key := $ordering }}
            {{-     $orderedKeys = append $orderedKeys (splitn "_" 2 $key)._1 }}
            {{-   end }}
            {{-   range $configKey := $orderedKeys }}
            - {{ printf "./service-config/%s.yaml" $configKey | quote }}
            {{-   end }}
            {{- end }}
          volumeMounts:
            - name: appsettings-configmap
              mountPath: "/sonar/sonar-agent/settings"
              readOnly: true
            - name: service-configmap
              mountPath: "/sonar/sonar-agent/service-config"
              readOnly: true
          env:
            - name: ApiKey
              valueFrom:
                secretKeyRef:
                  name: sonar-agent-secrets
                  key: apiKey
            - name: ENVIRONMENT
              value: k8s
            {{- if .Values.logLevel }}
            - name: Logging__LogLevel__Default
              value: {{ quote .Values.logLevel }}
            {{- end }}
            {{- if .Values.serviceAccountName }}
            - name: AgentConfig__InClusterConfig
              value: "true"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

