apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sonar-agent.fullname" . }}
  labels:
    {{- include "sonar-agent.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sonar-agent.fullname" . }}
  selector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonar-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: appsettings-configmap
          configMap:
            name: appsettings-configmap-file
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: service-configmap
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: service-configmap-file
            # An array of keys from the ConfigMap to create as files
            items:
              {{- range $config := .Values.configs }}
              - key: {{ $config.key }}
                path: {{ $config.key }}.yaml
              {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - {{ printf "--appsetting-location ./%s" $.Values.apiConfig.appsettingLocation }}
            {{- range $config := .Values.configs }}
            - {{ printf "./%s/%s.yaml" $.Values.apiConfig.serviceConfigLocation $config.key }}
            {{- end }}
          volumeMounts:
            - name: appsettings-configmap
              mountPath: {{ printf "/sonar/sonar-agent/%s" $.Values.apiConfig.appsettingLocation }}
            - name: service-configmap
              mountPath: {{ printf "/sonar/sonar-agent/%s" $.Values.apiConfig.serviceConfigLocation }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sonar-agent-secrets
                  key: apiKey
            - name: ENVIRONMENT
              value: k8s
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

