apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sonar-agent.fullname" . }}
  labels:
    {{- include "sonar-agent.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sonar-agent.fullname" . }}
  selector:
    matchLabels:
      {{- include "sonar-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonar-agent.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: sonar-agent-config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: sonar-agent
            # An array of keys from the ConfigMap to create as files
            items:
              {{- range $config := .Values.configs }}
              - key: {{ $config.key }}
                path: {{ $config.key }}.yaml
              {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- range $config := .Values.configs }}
            - {{ printf "./service-config/%s.yaml" $config.key | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/sonar/sonar-agent/service-config"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
        - volumeMounts:
          - name: appsettings-configmap
            mountPath: /sonar-agent
        - env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sonar-agent-secrets
                  key: apiKey
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: appsettings-configmap
          configMap:
            name: appsettings-configmap


