apiVersion: v2
name: sonar-agent
description: A Helm chart for Kubernetes
type: application

# The version of this helm chart
version: 0.5.3

# The version of sonar-agent this helm chart deploys
appVersion: "0.5.3"
