nameOverride: null

image:
  repository: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/oit/waynetech/sonar-agent
  pullPolicy: IfNotPresent

networkPolicies:
  enabled: true
  defaultAllowWithinCluster: true
  additionalEgressRules: []
  additionalIngressRules: []

imagePullSecrets: []

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

apiConfig:
  # The combination of environment & tenant should be unique per instance of the sonar-agent
  environment: example
  tenant: example
  baseUrl: http://sonar.sonar.svc.cluster.local:8081
  appsettingLocation: setting
  serviceConfigLocation: service-config

prometheus:
  host: localhost
  # Optional. Defaults to http / 9090
  protocol: null
  port: null

loki:
  host: localhost
  # Optional. Defaults to http / 3100
  protocol: null
  port: null

apikey: test+api+key+do+not+use+in+production+xxxxx=

# An array of service configurations that will be merged together in the order they are specified
configs: []
