nameOverride: null

image:
  repository: artifactory.cloud.cms.gov/batcave-docker/ado-repositories/oit/waynetech/sonar-agent
  # override to specify a specific image tag, defaults to the appVersion of the chart
  # tag: latest
  pullPolicy: IfNotPresent

networkPolicies:
  enabled: false
  defaultAllowWithinCluster: true
  additionalEgressRules: []
  additionalIngressRules: []

clusterRole:
  additionalRules:
    - apiGroups: ["kustomize.toolkit.fluxcd.io"]
      resources: [ "kustomizations" ]
      verbs: [ "get", "watch", "list" ]

# Use an existing secret for pulling images from the container registry
imagePullSecrets: []

# Create a secret from credential information (registry, email, username, password)
# This can be a single object with these keys, or an array of such objects.
registryCredentials: null

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

# The default log level: Error, Warning, Information, Debug, or Trace
logLevel: Information

apiConfig:
  # The combination of environment & tenant should be unique per instance of the sonar-agent
  environment: example
  tenant: example
  baseUrl: http://sonar.sonar.svc.cluster.local:8081
  apiKey: test+api+key+do+not+use+in+production+xxxxx=
  apiKeyId: 00000000-0000-0000-0000-000000000000
  reportingInterval: 30

prometheus:
  host: prometheus
  # Optional. Defaults to http / 9090
  protocol: null
  port: null

loki:
  host: loki
  # Optional. Defaults to http / 3100
  protocol: null
  port: null

# To enable sonar-argent to load configuration from your Kubernetes cluster set the
# kubernetesServiceConfig.enabled flag to true and specify a ServiceAccount name.
kubernetesServiceConfig:
  enabled: false
# This service account will be automatically created and granted permission to read Namespaces and
# ConfigMaps in all Namespaces.
serviceAccountName: null

# A dictionary of service configurations that will be merged together in the order they are specified
configs: {}
