prometheus:
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kube-state-metrics:
    enabled: false

  server:
    global:
      # scrape_interval and evaluation_interval should match props in sonar-api::Cms.BatCave.Sonar.Prometheus.IPrometheusService
      scrape_interval: 3m
      evaluation_interval: 1m

    alertmanagers:
      - static_configs:
          - targets: [ "sonar-api-alertmanager-headless:9093" ]

    resources:
      limits:
        cpu: 1
        memory: 2048Mi
      requests:
        cpu: 1
        memory: 2048Mi

    extraVolumeMounts:
      - name: config-rule-volume
        mountPath: /sonar-alerting-rules
    extraVolumes:
      - name: config-rule-volume
        configMap:
          name: sonar-alerting-rules
          optional: true

  serverFiles:
    prometheus.yml:
      rule_files:
        - "/etc/config/alerting_rules.yml"
        - "/sonar-alerting-rules/alerting-rules.yaml"
      scrape_configs:
        - job_name: "alertmanager"
          static_configs:
            - targets: [ "sonar-api-alertmanager-headless:9093" ]
    alerting_rules.yml:
      groups:
        - name: self-health-alerting
          rules:
            - alert: always-firing
              expr: vector(1)
              for: 0s
              labels:
                purpose: self-health-alerting
              annotations:
                description: An always-firing alert to ensure the alerting pathway from Prometheus to Alertmanager is working.

  configmapReload:
    prometheus:
      extraVolumeMounts:
        - name: config-rule-volume
          mountPath: /etc/config/sonar-alerting-rules

  alertmanager:
    enabled: true
    config:
      # Disable the creation of the default alertmanager config
      enabled: false
    imagePullSecrets:
      - name: artifactory-registry
    name: sonar-alertmanager
    image:
      #repository: artifactory.cloud.cms.gov/batcave-docker/ironbank/opensource/prometheus/alertmanager
      repository: prom/alertmanager
      tag: v0.25.0
    tolerations:
      - key: "sonar"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "bat_app"
        operator: "Equal"
        value: "sonar"
        effect: "NoSchedule"
    extraArgs:
      "config.file": "/sonar-config/alertmanager-config.yaml"
    configmapReload:
      enabled: true
      extraVolumeMounts:
        - name: config-secrets
          mountPath: /etc/alertmanager/secrets
    extraVolumeMounts:
      - name: config
        mountPath: /sonar-config
      - name: config-secrets
        mountPath: /sonar-config/secrets
      - name: templates
        mountPath: /sonar-config/templates
    extraVolumes:
      - name: config
        configMap:
          name: sonar-alertmanager-config
          optional: true
      - name: config-secrets
        secret:
          secretName: sonar-alerting-secrets
          optional: true
      - name: templates
        configMap:
          name: sonar-alertmanager-templates
