groups:
  - name: dev-alerts
    rules:
      - alert: alerting-test-app-is-offline
        expr: sonar_service_status{environment="foo",tenant="baz",service="alerting-test-app",sonar_service_status="Offline"} > 0
        for: 0s
        labels:
          purpose: service-alerting
          environment: foo
          tenant: baz
          service: alerting-test-app
        annotations:
          sonar_dashboard_uri: "http://localhost:8080/foo/tenants/baz/services/alerting-test-app"
      - alert: alerting-test-app-is-in-maintenance
        expr: sonar_service_maintenance_status{environment="foo",tenant="baz",service="alerting-test-app"} > 0
        for: 0s
        labels:
          environment: foo
          tenant: baz
          service: alerting-test-app
          purpose: maintenance
