apiVersion: v1
kind: ConfigMap
metadata:
  name: ado-2-sonar-config
  namespace: bar
  labels:
    sonar-config: "true"
    sonar-config/order: "2"
data:
  service-config.json: |
    {
      "services": [
        {
          "name": "test-metric-app2",
          "displayName": "Test Application",
          "description": "A test application that generates arbitrary metrics for testing purpose",
          "url": "http://localhost:2020/metrics",
          "children": null,
          "healthChecks": [
            {
              "name": "example",
              "description": "Degraded and Offline periodically based on an example metric.",
              "definition": {
                "duration": "0.00:00:20",
                "expression": "example_saw_wave",
                "conditions": [
                  {
                    "healthOperator": "GreaterThan",
                    "threshold": 60,
                    "healthStatus": "Offline"
                  },
                  {
                    "healthOperator": "GreaterThan",
                    "threshold": 20,
                    "healthStatus": "Degraded"
                  }
                ]
              },
              "type": "prometheusMetric"
            }
          ]
        }
      ],
      "rootServices": [
        "test-metric-app2"
      ]
    }
