apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ado-namespace-1
      labels:
        sonar-monitoring: "enabled"
        sonar-monitoring/tenant: "ado-1-tenant"
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: bar
      labels:
        sonar-monitoring: "enabled"
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: invalid-namespace-test
      labels:
        test-label: "test"
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: secret-test-namespace
      labels:
        sonar-monitoring: "enabled"
        sonar-config-secrets: "enabled"
        sonar-monitoring/tenant: "secret-test-tenant"
        test-label: "secrettest"

