{{- if .Values.serviceAccountName }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "clusterRoleName" . }}
rules:
  - apiGroups: [""]
    resources: [ "namespaces", "configmaps" ]
    verbs: [ "get", "watch", "list" ]
  {{- if .Values.clusterRole.additionalRules }}
{{ .Values.clusterRole.additionalRules | toYaml | indent 2 }}
  {{- end }}
{{- end }}
