{{- if .Values.serviceAccountName }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonar-agent-configmap-reader
rules:
  - apiGroups: [""]
    resources: [ "namespaces", "configmaps" ]
    verbs: [ "get", "watch", "list" ]
{{- end }}
