{{- if .Values.serviceAccountName }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonar-agent-global-read
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: sonar-agent-configmap-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
