{{- if .Values.serviceAccountName }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "clusterRoleName" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
