apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonar-ui.name" . }}
  labels:
    {{- include "sonar-ui.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "sonar-ui.selectorLabels" . | nindent 4 }}
