apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-api-settings
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning",
          "System.Net.Http.HttpClient.IPrometheusRemoteProtocolClient" : "Warning",
          "System.Net.Http.HttpClient.IAlertmanagerClient": "Warning"
        }
      },
      "Alerting": {
        "SmtpSettings": {
          "Sender": {{ quote .Values.sonarConfig.smtpSettings.sender }},
          "Host": {{ quote .Values.sonarConfig.smtpSettings.host }},
          "Port": {{ .Values.sonarConfig.smtpSettings.port }}
        }
      },
      "KubernetesApiAccess": {
        "IsEnabled": {{ .Values.sonarConfig.kubernetesApiAccess.isEnabled }},
        "IsInCluster": {{ .Values.sonarConfig.kubernetesApiAccess.isInCluster }},
        "TargetNamespace": {{ quote .Values.sonarConfig.kubernetesApiAccess.targetNamespace }}
      },
      "Okta": {
        "OktaDomain": {{ quote .Values.global.okta.oktaDomain }},
        "AuthorizationServerId": {{ quote .Values.global.okta.authorizationServerId }},
        "Audience": {{ quote .Values.global.okta.audience }}
      },
      "WebHost": {
        "AllowedOrigins": {{ .Values.sonarConfig.allowedOrigin | toJson }}
      },
      "Database": {
        {{- if .Values.sonarConfig.database.port }}
        "Port": {{ quote .Values.sonarConfig.database.port }},
        {{- end }}
        {{- if .Values.sonarConfig.database.protocol }}
        "Protocol": {{ quote .Values.sonarConfig.database.protocol }},
        {{- end }}
        "Host": {{ include "dbHost" . | quote }},
        "Username": {{ quote .Values.sonarConfig.database.username }}
      },
      "Prometheus": {
        {{- if .Values.sonarConfig.prometheus.port }}
        "Port": {{ quote .Values.sonarConfig.prometheus.host }},
        {{- end }}
        {{- if .Values.sonarConfig.prometheus.protocol }}
        "Protocol": {{ quote .Values.sonarConfig.prometheus.protocol }},
        {{- end }}
        "Host": {{ include "prometheusHost" . | quote }}
      },
      "Alertmanager": {
        {{- if .Values.sonarConfig.alertmanager.port }}
        "Port": {{ quote .Values.sonarConfig.alertmanager.port }},
        {{- end }}
        {{- if .Values.sonarConfig.alertmanager.protocol }}
        "Protocol": {{ quote .Values.sonarConfig.alertmanager.protocol }},
        {{- end }}
        "Host": {{ include "alertmanagerHost" . | quote }}
      },
      "SonarHealthCheck": {
        "SonarEnvironment": {{ quote .Values.sonarConfig.sonarEnvironment }}
      },
      "LegacyEndpoint": {
        "Enabled": {{ .Values.sonarConfig.legacyEndpoint.enabled }},
        {{- if .Values.sonarConfig.legacyEndpoint.serviceMapping }}
        "ServiceMapping":
          {{ .Values.sonarConfig.legacyEndpoint.serviceMapping | toJson }},
        {{- end }}
        {{- if .Values.sonarConfig.legacyEndpoint.rootServices }}
        "RootServices":
          {{ .Values.sonarConfig.legacyEndpoint.rootServices | toJson }}
        {{- end }}
      }
    }
