kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "roleName" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ include "roleName" . }}
  apiGroup: rbac.authorization.k8s.io
