apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "roleName" . }}
rules:
  - apiGroups: [""]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "*" ]
  {{- if .Values.role.additionalRules }}
{{ .Values.role.additionalRules | toYaml | indent 2 }}
  {{- end }}
