{{- if .Values.createSonarSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sonarSecretName }}
type: Opaque
data:
  DEFAULT_APIKEY: {{ b64enc .Values.sonarConfig.apiKey }}
  POSTGRES_PASSWORD: {{ b64enc .Values.sonarConfig.database.password }}
{{- end}}


