apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonar-api.fullname" . }}
  labels:
    {{- include "sonar-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sonar-api.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http

